import { Geist, Geist_Mono, Bebas_Neue, Outfit } from "next/font/google"; // ✅ tudo em um import
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const bebasNeue = Bebas_Neue({ weight: "400", subsets: ["latin"], variable: "--font-bebas" });
const outfit    = Outfit({ subsets: ["latin"], variable: "--font-outfit" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Lumos - Assista Infinitas histórias",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={`${bebasNeue.variable} ${outfit.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${outfit.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}